### ISSUE TITLE
 provide documentation for how to use mosquito with lucky

### ISSUE THREAD

**Issue by robacarp** [robacarp/mosquito#15]

**Comment by paulcockrell** [comment]
This would be great when you get around to it. Do you have an idea of when you might be able to produce the documentation for Lucky integration?

**Comment by robacarp** [comment]
@paulcockrell if it's something you're interested in, I can make it a higher priority. I don't think there is a big difference for any integration -- the standard [usage guide](https://github.com/robacarp/mosquito/blob/master/README.md#usage) may well be enough to get you up and running.

**Comment by paulcockrell** [comment]
Yes it would be helpful to have the documentation available. If you can promote it that would be ace. In the mean time ill give the standard usage guide a whirl as you suggest. Thanks.

**Comment by jwoertink** [comment]
https://dev.to/jwoertink/background-jobs-with-lucky-543p 

I'm now using this with lucky. Maybe my blog post will help?

**Comment by yunixon** [comment]
https://github.com/robacarp/mosquito/wiki/Usage:-Lucky
