### ISSUE TITLE
Wrong log snippet in Wikipages

### ISSUE THREAD

**Issue by duraki** [robacarp/mosquito#24]
Reading [logs](https://github.com/robacarp/mosquito/wiki/Queued-jobs#logs) paragraph on Wiki for this library and saw an error in the snippet code:

Should be: (replaced `puts` with `log`) 
```crystal
class PutsJob < Mosquito::QueuedJob
  def perform
    log "ohai background job"
  end
end

```

**Comment by robacarp** [comment]
Thanks @duraki, I've updated the wiki!
