### ISSUE TITLE
Using multiple params

### ISSUE THREAD

**Issue by jwoertink** [robacarp/mosquito#27]
I guess this isn't a thing? I'm assuming I have to make a special object and do my own custom serialization? If that's the case, then there may need to be a better error message for this.

```crystal
class AfterLoginWorker < Mosquito::QueuedJob
  params member_id : String
  params ip : String

  def perform
  end
end
```

```
web    | no argument named 'member_id'
web    | Matches are:
web    |  - AfterLoginWorker.new(ip : String)
web    |  - AfterLoginWorker.new() (trying this one)
```

**Comment by jwoertink** [comment]
If this is something you'd like to support, I can submit a PR for it.

**Comment by robacarp** [comment]
Perhaps it's counter intuitive, but you pass all the parameters you want into the same macro. This avoids depending on the finished macro hook.

```crystal
class AfterLoginWorker < Mosquito::QueuedJob
  params(member_id : String, ip : String)

  def perform
  # ...
  end
end
```

**Comment by jwoertink** [comment]
Ah. Ok. I'll give that a shot.

**Comment by jwoertink** [comment]
Alright, this works how I would expect. Cleaned up my code. I see you added the doc tag, so  that's good 👍  Thanks!

**Comment by robacarp** [comment]
Documented in the wiki now: https://github.com/robacarp/mosquito/wiki/Job-Parameters
