### ISSUE TITLE
Deleting key from redis doesn't recreate it on next run

### ISSUE THREAD

**Issue by greenbigfrog** [robacarp/mosquito#42]
I deleted a key of `waiting` type from redis via redis-cli to reset the queue, and now mosquito doesn't recreate it automatically and I can't queue any jobs of that type

**Comment by robacarp** [comment]
@greenbigfrog I don’t understand. When a task is moved into Waiting, the redis list is created. If some outside influences deleted the queue, mosquito will lose track of all the tasks it was holding — but there is nothing that can be done about that. 

 Can you be more specific about the way to reproduce?

**Comment by greenbigfrog** [comment]
> mosquito will lose track of all the tasks it was holding — but there is nothing that can be done about that.
That was my intention. I'll describe the way to reproduce soonish
