### ISSUE TITLE
Change the params api

### ISSUE THREAD

**Issue by watzon** [robacarp/mosquito#50]
It would be nice if you could just pass the params you want directly into the `perform` method. Basically take the api from:

```crystal
class MyWorker < Mosquito::QueuedJob
  params(param_one : String, other : String)

  def perform
  # ...
  end
end
``` 

to

```crystal
class MyWorker < Mosquito::QueuedJob
  def perform(param_one : String, other : String)
  # ...
  end
end
```

Just a way to simplify the API a bit.

**Comment by robacarp** [comment]
This isn't a bad idea, but I don't think it creates enough benefit to warrant the breaking change that it would cause to the API. Perhaps for version 1.0, after Crystal 1.0 arrives.
