### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by psikoz** [robacarp/mosquito#8]
Hey @robacarp 

I designed a logo for mosquito to contribute. If you want, i can send a pull-request. Also, Do you have a special color you want? I will wait for your comment. Best regards.

![mosquito](https://user-images.githubusercontent.com/40601249/42401429-3adfd030-817e-11e8-9c35-d62a1d90a1d6.jpg)

**Comment by robacarp** [comment]
@psikoz wow, thanks! 

My color of preference would be something which matches well with the Amber project logo. 

Is it possible to use a logo in svg format? I think it behaves better with git.

**Comment by psikoz** [comment]
I am glad you like it :) I applied amber colors. how are things?

![1](https://user-images.githubusercontent.com/40601249/42502892-e2296720-843f-11e8-93be-782a8396ab5c.jpg)

**Comment by robacarp** [comment]
@psikoz sorry, I miscommunicated. I actually like the red, just wanted to make sure it doesn't _clash_ with Amber. I do like the black text though. Red logo and black text and I'll ship it.

**Comment by psikoz** [comment]
I sent a pr with red logo and black text. Could you please check?
